@startuml name="initiate-transfer"

skinparam defaultFontSize 10
skinparam NoteFontSize 9
skinparam NoteFontName "Courier New"  ' Monospace font
skinparam wrapWidth 50                ' Set the width of the note

autonumber

actor "DFSP Customer" as Customer
participant "DFSP Customer App" as App
participant "Core Connector" as Core
participant "ML Connector" as ML

Customer ->> App: Customer transfer details.


App ->> Core: POST /send-money/ 
note left
{
    "homeTransactionId": "HTX123456789",
    "payeeId": "16135551212",
    "payeeIdType": "MSISDN",
    "sendAmount": "150.00",
    "sendCurrency": "MWK",
    "receiveCurrency": "ZMW",
    "purposeCode": "MP2P"
    "transactionType": "TRANSFER",
    "payer": {
        "name": "John Doe",
        "payerId": "9876543210"
    }
}
end note

Core ->> Core: Check Request

alt if Checks fail
    Core -->> App: Response 400
end



Core ->> ML: POST /transfers /{amountType: SEND} 
ML -->> Core: Response 200 [FXP Quote]
Core ->> Core: Check response

alt if WAITING_FOR_CONVERSION_ACCEPTANCE
    Core ->> Core: Validate FXP Quote

    alt Conversion terms are invalid
        Core ->> ML: PUT /transfers/{id}[acceptConversion: false]
        Core -->> App: Response 500
    end

    Core ->> ML: PUT /transfers/{id}[acceptConversion: true]
    
end

ML -->> Core: Response 200
Core ->> Core: Check Response

alt if WAITING_FOR_QUOTE_ACCEPTANCE
    Core ->> Core: Validate Normal Quote

    alt if Invalid Quote Terms
        Core -->> App: Response 500
    end
end

Core -->> App: Response 200 [Quote]
note right
{
    "payeeDetails": {
        "idType": "MSISDN",
        "idValue": "990454454",
        "fspId": "airtelzambia",
        "fspLEI": "984500BA13DAVB8B6C61"
        "name": "Niza"
    },
    "sendAmount": "150.00",
    "sendCurrency": "MWK",
    "receiveAmount": "140.00",
    "receiveCurrency": "ZMW",
    "targetFees": "10.00",
    "sourceFees": "10.00",
    "transactionId": "0GJGH201JGJ1J12324H",
    "homeTransactionId": "24dn186-sjhd-0293-44849-4724fhf",
}
end note

App -->> Customer: Terms of transfer

@enduml
