@startuml name="payee-quote-request"

skinparam defaultFontSize 10
autonumber

participant "ML Connector" as ML
participant "Core Connector" as CC
participant "Blue Bank API" as SBAPI

ML ->> CC: POST /quote-requests/{}

alt if required fields missing
    CC -->> ML: Response 400 Bad Request
end

CC ->> CC: Validation Check,\nQuote Validation,\nExpiration Check

alt if Id Type invalid
    CC -->> ML: Response 400 Bad Request
end

alt if Currency Not Supported
    CC -->> ML: Response 500
end

CC ->> SBAPI: GET /accounts/{partyIdentifier}

SBAPI -->> CC: Response
note right
{
  "success": true,
  "data": {
    "accountId": "260970000000",
    "name": "Mercy Uzumaki",
    "currency": "ZMW",
    "isActive": true
  }
}
end note

CC ->> CC: Response Check

alt If Response is Not Successful
    CC -->> ML: Response 500
end

alt If No Party found
    CC -->> ML: Response 404
end

CC ->> SBAPI: POST /quotes
note left
{
  "account_id": "260970000000",
  "amount": 100.0,
  "currency": "ZMW"
}
end note


SBAPI -->> CC: Response 200 [Qoute]
note right
{
  "success": true,
  "data": {
    "amount": 100.0,
    "fee": 1.0,
    "currency": "ZMW"
  }
}
end note

CC ->> CC: Calculate Charge


note right
{
    "canTransferProceed": true,
}
end note


CC ->> CC: Due Diligence Check
alt if canTransferProceed == false
    CC -->> ML: Response 500
end

CC ->> CC: Prepare Response
CC -->> ML: Response 200
@enduml
