@startuml name="ml-transfer-reservation-commit"

skinparam defaultFontSize 10
autonumber

participant "ML Connector" as ML
participant "Core Connector" as CC
participant "Blue Bank API" as SBAPI

ML ->> CC: POST /transfers/ {}

CC ->> CC: Validation Checks, Expiration Check,\nQuote Expiration Validation,\nCurrency Conversion Checks

alt if Checks Fail
    CC -->> ML: Response 500
end

CC ->> SBAPI: GET /accounts/{partyIdentifier}

note over SBAPI
{
  "success": false,
  "error": {
    "code": 404,
    "message": "Account not found"
  }
}
end note
SBAPI -->> CC: Response

CC ->> CC: Check response and customer account status

alt if Customer account has issues
    CC -->> ML: Response 500, mlCode: 5400
end


CC ->> SBAPI: POST /funds/reserve
note left
{
  "success": true,
  "data": {
    "reserveId": "3c5d424b-21e5-4d97-9694-6aa4dc62f7a4",
    "status": "RESERVED"
  }
}
end note


SBAPI -->> CC: Response
note right
{
  "success": true,
  "data": {
    "reserveId": "e4c63007-0348-4962-ae39-32ba656f20bf",
    "status": "RESERVED"
  }
}
end note

alt if Reservation Not Successful
    CC -->> ML: Response 500, mlCode: 5400
end

CC -->> ML: Response 200 [RESERVED]

ML ->> CC: PUT /transfers/{id}


alt if Current State !== COMPLETED
   
    CC ->> SBAPI: POST /funds/unreserve
    note left
        {
        "reserve_id": "REPLACE_ME",
        "reason": "downstream transfer failed"
        }
    end note

    
    SBAPI -->> CC: Response 200
    note right
   {
    "success": true,
    "data": {
        "reserveId": "f7f64a01-8281-4471-8790-5ad3834a8838",
        "status": "RELEASED"
    }
    }
    end note
    CC -->> ML: Response 500
end


CC ->> SBAPI: POST /funds/commit
note left
{
  "reserve_id": "REPLACE_ME"
}
end note

SBAPI -->> CC: Response
note right
{
  "success": true,
  "data": {
    "reserveId": "0586afca-2347-4b58-8aa9-6f2f44c5f10b",
    "status": "COMMITTED"
  }
}
end note

CC ->> CC: Check response

alt if status != COMMITTED
    CC -->> ML: Response 500
end

CC -->> ML: Response 200
@enduml
