name: Docker
run-name: Docker => ${{  github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message }}

permissions:
  contents: read
  packages: write
  pull-requests: write
  security-events: write
  
on:
  push:
    tags: ["v*.*.*"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            image: bluebank-zm-dfsp-cc
            context: .
          # - dockerfile: cbs-mock/Dockerfile
          #   image: bluebank-zm-dfsp-cc-cbs-mock
          #   context: ./cbs-mock
    uses: JengaCore/actions/.github/workflows/docker.yaml@main
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image: ${{ matrix.image }}
      context: ${{ matrix.context }}
      registry: docker.io
      owner: thewababa
    secrets:
      REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
